#!/usr/local/sbin/charm-env python3
"""
Upgrade services running in docker.

Pull latest version from registry
and replace currently running containers
with this latest version.
"""

from charmhelpers.core.hookenv import log


if __name__ == "__main__":
    try:
        log('Get admin credentials')
        with open('/root/.alertarc', 'r') as f:
            contents = f.read()
            print(contents)
    except IOError:
        log('IOError: {}'.format('/root/.alertarc'), level="ERROR")
